WITH CONTACT_TEAM AS
(SELECT DISTINCT CONTACT_TEAM_MEMBER AS CONTACT_TEAM_MMBR, NPI,ACCT_TYPE
      FROM COMN_STG.SF_PHYSICIAN
      WHERE EXPR_DTS IS NULL
    UNION ALL
    SELECT DISTINCT CONTACT_TEAM_MEMBER2 AS CONTACT_TEAM_MMBR,NPI,ACCT_TYPE
      FROM COMN_STG.SF_PHYSICIAN
      WHERE EXPR_DTS IS NULL
      AND CONTACT_TEAM_MEMBER2 IS NOT NULL)      
      SELECT count(1) FROM CONTACT_TEAM (
 SELECT 
  DISTINCT LIAISON_NAME AS CONTACT_TEAM_MMBR,NPI,ACCT_TYPE,'a' 
      FROM COMN_STG.SF_SECURITY_BO_SALESFORCE,CONTACT_TEAM
     WHERE POWER_USER = 'Y'
     AND EXPR_DTS IS NULL
     union all
 SELECT CONTACT_TEAM_MMBR, NPI,ACCT_TYPE, 'B'
 FROM CONTACT_TEAM 
) P 
